### ISSUE TITLE
Notes while reading through

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/ml_molsim2020#13]
Will update this as I go along

 - [X] I would suggest to move the kaggle instructions to the Jupyter notebook. They are not needed to get started and I'm not sure people will see them so far down in the README
 - [ ] 1: Since you now add some information about the autocorrelation descriptors, perhaps 1-2 questions would make sense that check that people have a basic understanding of them
 - [X] 1: "The number shows the coordination shell that was considered in the calculation of the RACs." - unclear which number
 - [X] 1: Besides the description of the features, add one sentence on the target property (what it means, including units)

**Comment by ltalirz** [comment]
also done here

**Comment by ltalirz** [comment]
Some more questions that came to my mind while reading through:
 * is there a way to print how many parameters e.g. our KRR model contains?
 * I didn't see any mention of how protect against overfitting. it might be quite easy to add a short exercise to compare performance on the test and training data sets, perhaps with some more hints

**Comment by kjappelbaum** [comment]
> I didn't see any mention of how to protect against overfitting. it might be quite easy to add a short exercise to compare performance on the test and training data sets, perhaps with some more hints

Oh, we might have to make this clearer. This is the stuff with $\alpha$ and the optional regularization exercise. But, yea, there are more approaches to do this.

> is there a way to print how many parameters (not hyperparameters) e.g. our KRR model contains?
this is a good question we should ask! Basically this are the elements of Kernel matrix (n_samples, n_samples)  and the weights (`dual_coef_` attribute (n_samples, ))

**Comment by kjappelbaum** [comment]
I'm closing this issue now, many thanks for your help!
