### ISSUE TITLE
Questions while reading

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/ml_molsim2020#6]
- [X] Section 0: why *revised* autocorrelation functions?
 - [X] Section 0: Move anything to do with target/feature columns *after* you have imported the data
 - [ ] Section 1: perhaps plot CO2 deliverable capacity against Di 
 - [X] Section 1: if they want to see all features, use something like `pd.options.display.max_columns=10`

**Comment by kjappelbaum** [comment]
For `Section 1: perhaps plot CO2 deliverable capacity against Di` I wouldn't like to do it before the train-test split to be super consistent.

**Comment by kjappelbaum** [comment]
`Section 0: why revised autocorrelation functions?`: This is covered in the lecture by Mohamad, but I will add one more comment.

**Comment by kjappelbaum** [comment]
`Section 1: if they want to see all features, use something like pd.options.display.max_columns=10` Thanks, I will add this as hint, but in section 1 I do not want them to have a detailed look. Maybe I need to make this clearer. The look into the data should only happen after the train/test split.

**Comment by kjappelbaum** [comment]
Thanks, really useful feedback!

**Comment by ltalirz** [comment]
> For Section 1: perhaps plot CO2 deliverable capacity against Di I wouldn't like to do it before the train-test split to be super consistent.

That was a suggestion by Mohamad, but I think he would be fine to do this after the split between test and training data.

I'll close this now - I'll open another one on monday
