### ISSUE TITLE
adding elements of achievement to the exercise?

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/ml_molsim2020#8]
some ideas how one can add elements of achievement to the exercise

### performance targets
one simple way of doing that would be to set two targets for some performance metric e.g. the MAE - one that is easily reached in the exercise as long as one doesn't do bad mistakes, and one that might need some of the more advanced techniques mentioned (I don't know e.g. whether gradient boost techniques yield significantly better results).
while it's true that you won't know these targets when you start out on a new data set, this is an exercise and it's useful to show people whether they are doing some mistake.

the more elaborate version of this would be to try and open an ML competition on an open site like [codalab](https://codalab.org/) (see [instructions](https://github.com/codalab/codalab-competitions/wiki/User_Running-a-Competition) where they can (optionally) upload their model.

### let them predict on a data set where they don't know the target properties
Have another part of the data set (either as part of the repo or ready for download), which only contains the features, that they can use to actually use the model to make predictions, and then ask questions about the performance of these structures (e.g. what is the best performing structure, etc.)

**Comment by kjappelbaum** [comment]
This is a great idea, I just started trying to use Kaggle for this 'in classroom' competition. I would like to use Kaggle as it is the best place to learn data science.

**Comment by ltalirz** [comment]
Right, I looked at kaggle first as well but I missed the "in classroom" link so I thought they don't do these type of competitions. All the better!

**Comment by ltalirz** [comment]
I'm sure Berend would be happy to sponsor one of his books as a prize ;)

**Comment by kjappelbaum** [comment]
the Kaggle completion is open http://www.kaggle.com/c/molsim2020. We still need to figure out 
- [  ] how long do we run the competition (in theory we could let it open until Nicola's lecture) 
- [  ] prizes other than the CCS book 
- [  ] do we need more explanation for Kaggle?

**Comment by ltalirz** [comment]
very cool! 

> how long do we run the competition (in theory we could let it open until Nicola's lecture)

Hehe, I do think Nicola wouldn't mind at all handing out a prize (or you handing it out) - that sounds like a nice idea.

Technically how does this work, i.e. can students still submit things after the end of the competition (of course without winning the prize)?

If not, I would keep it open for, say, a week longer so that people who are really interested in it but didn't manage during the day can still have a go when they're back home.
In that case you could simply communicate the time by when the winner will be determined.

> prizes other than the CCS book

you mean for 2nd/3rd?
hm... I guess the top results will likely be from people who already has quite some ML experience, so perhaps better not something related to ML.
perhaps something local & edible from Amsterdam? ;-)

> do we need more explanation for Kaggle?

I'll have a go on Monday, I'll let you know in case

**Comment by ltalirz** [comment]
> do we need more explanation for Kaggle?

One question - do you really need to mention the Kaggle API?
I think you have nicely explained how to submit the results via the browser - I would guess that people who feel for some reason they want to use the API can figure this out on their own.

**Comment by kjappelbaum** [comment]
> One question - do you really need to mention the Kaggle API?

Deleted it.

**Comment by kjappelbaum** [comment]
> you mean for 2nd/3rd?
Yes, let's see if I see something local tomorrow ...

**Comment by kjappelbaum** [comment]
> Technically how does this work on kaggle, i.e. can students still submit things after you officially end the competition (of course without winning the prize)?

Yes, technically, the submissions close Thursday midnight, which freezes the leaderboard. But the evaluation should still work.

**Comment by ltalirz** [comment]
> Yes, technically, the submissions close Thursday midnight, which freezes the leaderboard. But the evaluation should still work.

Ok, as long as people can still use it, that's fine.

I think this issue has been addressed quite nicely ;-)
