### ISSUE TITLE
give students a way to look at structures?

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/ml_molsim2020#9]
so far, the structures are 'anonymous' rows in a table.

if they had a way to visualize a structure from knowing their ID,  this would open a new avenue for asking questions about structure/property relationships.

how big would the archive of CIF files be?

An alternative would be to put the structures on some server and run a jsmol app that knows about their location and loads a structure when pass the ID via a URL parameter - just like [here](https://discover.materialscloud.org/cofs/detail?name=linker91_C_linker91_C_tbd_relaxed).
in that case, the notebook is, however, no longer self-contained.

**Comment by kjappelbaum** [comment]
Good idea, haven't looked at it due to lack of time. If I find the time, I will write some dashboard. Otherwise we can just the link to materials cloud, which should be in the exercise notes. (It is Pete's data).  

I will certainly link to the interactive plots on Materials Cloud for the EDA part. 

Many thanks for your time and input!

**Comment by ltalirz** [comment]
> It is Pete's data

You mean this data?
https://www.materialscloud.org/discover/mofs
https://discover.materialscloud.org/mofs/detail?name=str_m2_o10_o28_pcu_sym.58&table=top_mofs

Then the solution already exists, you just need to have the structure name as a column in the data.

**Comment by kjappelbaum** [comment]
Indeed, the "MOFname" is already a column of the dataset. I added the link to Materials Cloud in https://github.com/kjappelbaum/ml_molsim2020/commit/1f881c5b4ccbe9b2a14cabce3ec5396f1f42024d. 

Many thanks!

**Comment by ltalirz** [comment]
> the "MOFname" is already a column of the dataset

I'm afraid it's not quite that simple - e.g. the first name is "ABEXEM_clean" while the names on materials cloud are of the form str_m2_o10_o28_pcu_sym.58
Might make sense to have another column with the names used there

**Comment by kjappelbaum** [comment]
I'll double check but there was an update in the dataset since you had a look at it.

**Comment by ltalirz** [comment]
ah sorry, it's fixed - very good!

**Comment by ltalirz** [comment]
just for the record, here is a python snippet to view a structure in the browser (we might not need it)
```python
def view_structure(name):
    import webbrowser
    webbrowser.open(f'https://discover.materialscloud.org/mofs/detail?name={name}', new=2)
view_structure('str_m2_o10_o29_pcu_sym.69')
```
webbrowser is in the standard library - didn't know!
